<?php 
/**
 * @version		1.0
 * @Project		Facebook Like Box
 * @author 		Sunento Wu	
 * @package		
 * @copyright	Copyright (C) 2010 Vivociti.com. All rights reserved.
 * @license 	http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU/GPL version 2
 * URL : http://vivociti.com
* Description : Facebook Like Box is a social module that enables Facebook Page owners to attract and gain Likes from their own website. The Like Box enables users to: see how many users already like this page, and which of their friends like it too, read recent posts from the page and Like the page with one click, without needing to visit the page
* Generated By : YouCMSAndBlog IDE Joomla Module Plugin (http://vivociti.com)
* (please support YouCMSAndBlog by promoting it, dont remove above line. Thanks.)
* WE LOVE JOOMLA! 
*/
/// no direct access 
defined('_JEXEC') or die('Restricted access'); 
//Get parameters 
//The ID of the Facebook Page for this Like Box
$pageID = $params->get('pageID', '123961057630124'); 
//The Width of the module in pixes
$width = $params->get('width'); 
$height = $params->get('height'); 
//Show a sample of this many users who have liked this Page
$connection = $params->get('connection'); 
//Show the profile stream for Public Profile
$streams = $params->get('streams'); 
//Show the Find Us on Facebook bar at top. Only shown when either stream or connections are present
$header = $params->get('header'); 
//Show Author Credit, this is free module
$moduleBy = $params->get('moduleBy'); 

if ($streams == "yes") {
	$streams = "true";
	$height = $height + 300;
} else {
	$streams = "false";
}

if ($header == "yes") {
	$header = "true";
	$height = $height + 32;
} else {
	$header = "false";
}

$width='205';
?>
<iframe src="http://www.facebook.com/plugins/likebox.php?id=<?php echo $pageID;?>&amp;width=<?php echo $width;?>&amp;connections=<?php echo $connection;?>&amp;stream=<?php echo $streams;?>&amp;header=<?php echo $header;?>&amp;height=<?php echo $height;?>" scrolling="no" frameborder="0" style="border:1px solid #a4b562; margin-bottom:3px; padding:none;box-shadow: 2px 2px 2px #333;-webkit-box-shadow: 2px 2px 2px #333; -moz-box-shadow: 2px 2px 2px #333; overflow:hidden; width:<?php echo $width;?>px; height:<?php echo $height;?>px; background:#FFFFFF;" allowTransparency="true">



</iframe>

<?php
	if ($moduleBy == "yes") {
?>
<a name="fb_share" type="icon_link" share_url="http://vivociti.com" href="http://www.facebook.com/sharer.php">Share</a><script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share" type="text/javascript"></script>
<?php
}
?>


